[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19"
reqwasm = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
yew-router = "0.16"
log = "0.4.17"
wasm-logger = "0.2.0"
